### ISSUE TITLE
关于模版变量输出的疑问

### ISSUE THREAD

**Issue by netbuffer** [sentsin/laytpl#9]
````<a href="http://www.xxx.com?id={{d.num/10}}"></a>````，我想实现这个效果，可是变量输出不支持运算，是不是一定要用js去取值，再dom操作赋值操作？请指教哈

**Comment by netbuffer** [comment]
@sentsin 能否指教下~

**Comment by sentsin** [comment]
{{ 里面支持单个表达式 }}

**Comment by netbuffer** [comment]
额,不知道 之前怎么回事，一直没运行运算,今天试了下，又可以了
